platform :ios, '6.0'
pod 'SSKeychain', '~> 1.2.0'
pod 'SocketRocket', '~> 0.3.1-beta2'
pod 'Reachability', '~> 3.1.1'
pod 'EGOTableViewPullRefresh', '~> 0.1.0'
pod 'AFNetworking', '~> 1.3.2'
pod 'MBProgressHUD', '~> 0.7'
pod 'OpenTokSDK-WebRTC', '~> 2.1.4'
pod 'FlatUIKit', '~> 1.2'
pod 'PKRevealController', '~> 1.0b2'
pod 'CocoaLumberjack', '~> 1.6.2'
pod 'OBShapedButton', '~> 1.0.2'

target :RenHaiGHUnitTest do
	pod 'GHUnitIOS', '~> 0.5.6'
end
