platform :ios, '6.0'
pod 'SSKeychain', '~> 1.2.1'
pod 'SocketRocket', '~> 0.3.1-beta2'
pod 'Reachability', '~> 3.1.1'
pod 'AFNetworking', '~> 1.3.3'
pod 'MBProgressHUD', '~> 0.8'
pod 'OpenTokSDK-WebRTC', '~> 2.1.6'
pod "FlatUIKit", :git => "https://github.com/Grouper/FlatUIKit.git"
pod 'PKRevealController', '~> 2.0.5'
pod 'CocoaLumberjack', '~> 1.6.2'
pod 'OBShapedButton', '~> 1.0.2'
pod 'DraggableCollectionView', '~> 0.1'
pod 'CWPopup', '~> 1.2.5'
pod 'AutoScrollLabel', '~> 0.2.1'
pod 'FloatingClouds', :git => 'https://github.com/satgi/FloatingCloudsView.git'
pod 'KXKiOS7ColorsAndGradients', '~> 1.0.0'

target :RenHaiGHUnitTest do
        pod 'GHUnitIOS', '~> 0.5.8'
end