package com.simplelife.renhai.server.db;

import org.apache.ibatis.session.SqlSession;

import com.simplelife.renhai.server.util.IDbObject;

public class Devicecard implements IDbObject 
{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicecard.deviceCardId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Integer deviceCardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicecard.deviceId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Integer deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicecard.registerTime
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Long registerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicecard.deviceModel
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private String deviceModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicecard.osVersion
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private String osVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicecard.appVersion
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private String appVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicecard.location
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicecard.isJailed
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private String isJailed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicecard.deviceCardId
     *
     * @return the value of devicecard.deviceCardId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Integer getDeviceCardId() {
        return deviceCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicecard.deviceCardId
     *
     * @param deviceCardId the value for devicecard.deviceCardId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setDeviceCardId(Integer deviceCardId) {
        this.deviceCardId = deviceCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicecard.deviceId
     *
     * @return the value of devicecard.deviceId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicecard.deviceId
     *
     * @param deviceId the value for devicecard.deviceId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicecard.registerTime
     *
     * @return the value of devicecard.registerTime
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Long getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicecard.registerTime
     *
     * @param registerTime the value for devicecard.registerTime
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setRegisterTime(Long registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicecard.deviceModel
     *
     * @return the value of devicecard.deviceModel
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public String getDeviceModel() {
        return deviceModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicecard.deviceModel
     *
     * @param deviceModel the value for devicecard.deviceModel
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setDeviceModel(String deviceModel) {
        this.deviceModel = deviceModel == null ? null : deviceModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicecard.osVersion
     *
     * @return the value of devicecard.osVersion
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public String getOsVersion() {
        return osVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicecard.osVersion
     *
     * @param osVersion the value for devicecard.osVersion
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setOsVersion(String osVersion) {
        this.osVersion = osVersion == null ? null : osVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicecard.appVersion
     *
     * @return the value of devicecard.appVersion
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public String getAppVersion() {
        return appVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicecard.appVersion
     *
     * @param appVersion the value for devicecard.appVersion
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion == null ? null : appVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicecard.location
     *
     * @return the value of devicecard.location
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicecard.location
     *
     * @param location the value for devicecard.location
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicecard.isJailed
     *
     * @return the value of devicecard.isJailed
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public String getIsJailed() {
        return isJailed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicecard.isJailed
     *
     * @param isJailed the value for devicecard.isJailed
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setIsJailed(String isJailed) {
        this.isJailed = isJailed == null ? null : isJailed.trim();
    }

	@Override
	public void save(SqlSession session)
	{
		DevicecardMapper mapper = session.getMapper(DevicecardMapper.class);
		if (this.deviceCardId == null)
		{
			mapper.insert(this);
		}
		else
		{
			mapper.updateByPrimaryKey(this, deviceCardId);
		}
	}
}