package com.simplelife.renhai.server.db;

import org.apache.ibatis.session.SqlSession;

import com.simplelife.renhai.server.util.IDbObject;

public class Globalimpresslabel implements IDbObject 
{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column globalimpresslabel.globalImpressLabelId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Integer globalImpressLabelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column globalimpresslabel.impressLabelName
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private String impressLabelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column globalimpresslabel.globalAssessCount
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Integer globalAssessCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column globalimpresslabel.globalImpressLabelId
     *
     * @return the value of globalimpresslabel.globalImpressLabelId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Integer getGlobalImpressLabelId() {
        return globalImpressLabelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column globalimpresslabel.globalImpressLabelId
     *
     * @param globalImpressLabelId the value for globalimpresslabel.globalImpressLabelId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setGlobalImpressLabelId(Integer globalImpressLabelId) {
        this.globalImpressLabelId = globalImpressLabelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column globalimpresslabel.impressLabelName
     *
     * @return the value of globalimpresslabel.impressLabelName
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public String getImpressLabelName() {
        return impressLabelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column globalimpresslabel.impressLabelName
     *
     * @param impressLabelName the value for globalimpresslabel.impressLabelName
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setImpressLabelName(String impressLabelName) {
        this.impressLabelName = impressLabelName == null ? null : impressLabelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column globalimpresslabel.globalAssessCount
     *
     * @return the value of globalimpresslabel.globalAssessCount
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Integer getGlobalAssessCount() {
        return globalAssessCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column globalimpresslabel.globalAssessCount
     *
     * @param globalAssessCount the value for globalimpresslabel.globalAssessCount
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setGlobalAssessCount(Integer globalAssessCount) {
        this.globalAssessCount = globalAssessCount;
    }

	@Override
	public void save(SqlSession session)
	{
		GlobalimpresslabelMapper mapper = session.getMapper(GlobalimpresslabelMapper.class);
		if (this.globalImpressLabelId != null)
		{
			mapper.updateByPrimaryKey(this);
		}
		else
		{
			IDbObject label = mapper.selectByStringKey(impressLabelName);
			if (label == null)
			{
				mapper.insert(this);
			}
			else
			{
				mapper.updateByPrimaryKey(this);
			}
		}
	}
	
	@Override
	public Globalimpresslabel clone()
	{
		Globalimpresslabel label = new Globalimpresslabel();
		label.setGlobalAssessCount(globalAssessCount);
		label.setGlobalImpressLabelId(globalImpressLabelId);
		label.setImpressLabelName(impressLabelName);
		return label;
	}
}