package com.simplelife.renhai.server.db;

public class Hotinterestlabelstatistics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotinterestlabelstatistics.hotInterestLabelStatisticsId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Integer hotInterestLabelStatisticsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotinterestlabelstatistics.saveTime
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Long saveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotinterestlabelstatistics.globalInterestLabelId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Integer globalInterestLabelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotinterestlabelstatistics.count
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotinterestlabelstatistics.hotInterestLabelStatisticsId
     *
     * @return the value of hotinterestlabelstatistics.hotInterestLabelStatisticsId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Integer getHotInterestLabelStatisticsId() {
        return hotInterestLabelStatisticsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotinterestlabelstatistics.hotInterestLabelStatisticsId
     *
     * @param hotInterestLabelStatisticsId the value for hotinterestlabelstatistics.hotInterestLabelStatisticsId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setHotInterestLabelStatisticsId(Integer hotInterestLabelStatisticsId) {
        this.hotInterestLabelStatisticsId = hotInterestLabelStatisticsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotinterestlabelstatistics.saveTime
     *
     * @return the value of hotinterestlabelstatistics.saveTime
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Long getSaveTime() {
        return saveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotinterestlabelstatistics.saveTime
     *
     * @param saveTime the value for hotinterestlabelstatistics.saveTime
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setSaveTime(Long saveTime) {
        this.saveTime = saveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotinterestlabelstatistics.globalInterestLabelId
     *
     * @return the value of hotinterestlabelstatistics.globalInterestLabelId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Integer getGlobalInterestLabelId() {
        return globalInterestLabelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotinterestlabelstatistics.globalInterestLabelId
     *
     * @param globalInterestLabelId the value for hotinterestlabelstatistics.globalInterestLabelId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setGlobalInterestLabelId(Integer globalInterestLabelId) {
        this.globalInterestLabelId = globalInterestLabelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotinterestlabelstatistics.count
     *
     * @return the value of hotinterestlabelstatistics.count
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotinterestlabelstatistics.count
     *
     * @param count the value for hotinterestlabelstatistics.count
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}