package com.simplelife.renhai.server.db;

import org.apache.ibatis.session.SqlSession;

import com.simplelife.renhai.server.util.IDbObject;

public class Interestlabelmap implements IDbObject, Comparable<Interestlabelmap> 
{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interestlabelmap.interestLabelMapId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Integer interestLabelMapId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interestlabelmap.interestCardId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Integer interestCardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interestlabelmap.globalInterestLabelId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Integer globalInterestLabelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interestlabelmap.labelOrder
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Integer labelOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interestlabelmap.matchCount
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Integer matchCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interestlabelmap.validFlag
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private String validFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interestlabelmap.interestLabelMapId
     *
     * @return the value of interestlabelmap.interestLabelMapId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Integer getInterestLabelMapId() {
        return interestLabelMapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interestlabelmap.interestLabelMapId
     *
     * @param interestLabelMapId the value for interestlabelmap.interestLabelMapId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setInterestLabelMapId(Integer interestLabelMapId) {
        this.interestLabelMapId = interestLabelMapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interestlabelmap.interestCardId
     *
     * @return the value of interestlabelmap.interestCardId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Integer getInterestCardId() {
        return interestCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interestlabelmap.interestCardId
     *
     * @param interestCardId the value for interestlabelmap.interestCardId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setInterestCardId(Integer interestCardId) {
        this.interestCardId = interestCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interestlabelmap.globalInterestLabelId
     *
     * @return the value of interestlabelmap.globalInterestLabelId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Integer getGlobalInterestLabelId() {
        return globalInterestLabelId;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interestlabelmap.globalInterestLabelId
     *
     * @param globalInterestLabelId the value for interestlabelmap.globalInterestLabelId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setGlobalInterestLabelId(Integer globalInterestLabelId) {
        this.globalInterestLabelId = globalInterestLabelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interestlabelmap.labelOrder
     *
     * @return the value of interestlabelmap.labelOrder
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Integer getLabelOrder() {
        return labelOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interestlabelmap.labelOrder
     *
     * @param labelOrder the value for interestlabelmap.labelOrder
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setLabelOrder(Integer labelOrder) {
        this.labelOrder = labelOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interestlabelmap.matchCount
     *
     * @return the value of interestlabelmap.matchCount
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Integer getMatchCount() {
        return matchCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interestlabelmap.matchCount
     *
     * @param matchCount the value for interestlabelmap.matchCount
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setMatchCount(Integer matchCount) {
        this.matchCount = matchCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interestlabelmap.validFlag
     *
     * @return the value of interestlabelmap.validFlag
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public String getValidFlag() {
        return validFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interestlabelmap.validFlag
     *
     * @param validFlag the value for interestlabelmap.validFlag
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setValidFlag(String validFlag) {
        this.validFlag = validFlag == null ? null : validFlag.trim();
    }
    
    @Override
	public void save(SqlSession session)
	{
 		InterestlabelmapMapper mapper = session.getMapper(InterestlabelmapMapper.class);
 		if (this.interestLabelMapId == null)
		{
 			if (this.globalInterestLabelId == null)
			{
 				if (globalLabel == null)
				{
					DBModule.instance.getLogger().error("Fatal error: globalLabel == null when trying to save InterestlabelmapMapper");
					return;
				}
 				
				Integer id = globalLabel.getGlobalInterestLabelId(); 
				if (id == null)
				{
					globalLabel.save(session);
					id = globalLabel.getGlobalInterestLabelId();
				}
				this.globalInterestLabelId = id;
			}
			mapper.insert(this);
		}
		else
		{
			mapper.updateByPrimaryKey(this);
		}
	}
	
	public void delete(SqlSession session)
	{
		InterestlabelmapMapper mapper = session.getMapper(InterestlabelmapMapper.class);
		mapper.deleteByPrimaryKey(interestLabelMapId);
	}
	
	public void setGlobalLabel(Globalinterestlabel label)
	{
		globalLabel = label;
	}
	
	public Globalinterestlabel getGlobalLabel()
	{
		/*
		if (globalLabel == null)
		{
			globalLabel = DBQueryUtil.getGlobalinterestlabel(globalInterestLabelId);
		}
		*/
		return globalLabel;
	}
	
	private Globalinterestlabel globalLabel = null;

	@Override
	public int compareTo(Interestlabelmap o)
	{
		if (o == null)
		{
			return 1;
		}
		return labelOrder.compareTo(o.getLabelOrder());
		/*
		Integer targetId = o.getInterestLabelMapId();
		if (interestLabelMapId == null && targetId == null)
		{
			String labelName = globalLabel.getInterestLabelName();
			String targetLabelName = o.getGlobalLabel().getInterestLabelName(); 
			return labelName.compareTo(targetLabelName);
		}
		
		if (interestLabelMapId == null || targetId == null)
		{
			return -1;
		}
		return (interestLabelMapId - targetId);
		*/
	}
}