package com.simplelife.renhai.server.db;

import java.util.concurrent.ConcurrentLinkedQueue;

import org.apache.ibatis.session.SqlSession;

import com.simplelife.renhai.server.util.IDbObject;

public class Profile implements IDbObject 
{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.profileId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Integer profileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.deviceId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Integer deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.serviceStatus
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private String serviceStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.unbanDate
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Long unbanDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.lastActivityTime
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Long lastActivityTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.createTime
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.active
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private String active;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.profileId
     *
     * @return the value of profile.profileId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Integer getProfileId() {
        return profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.profileId
     *
     * @param profileId the value for profile.profileId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setProfileId(Integer profileId) {
        this.profileId = profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.deviceId
     *
     * @return the value of profile.deviceId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.deviceId
     *
     * @param deviceId the value for profile.deviceId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.serviceStatus
     *
     * @return the value of profile.serviceStatus
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public String getServiceStatus() {
        return serviceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.serviceStatus
     *
     * @param serviceStatus the value for profile.serviceStatus
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setServiceStatus(String serviceStatus) {
        this.serviceStatus = serviceStatus == null ? null : serviceStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.unbanDate
     *
     * @return the value of profile.unbanDate
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Long getUnbanDate() {
        return unbanDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.unbanDate
     *
     * @param unbanDate the value for profile.unbanDate
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setUnbanDate(Long unbanDate) {
        this.unbanDate = unbanDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.lastActivityTime
     *
     * @return the value of profile.lastActivityTime
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Long getLastActivityTime() {
        return lastActivityTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.lastActivityTime
     *
     * @param lastActivityTime the value for profile.lastActivityTime
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setLastActivityTime(Long lastActivityTime) {
        this.lastActivityTime = lastActivityTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.createTime
     *
     * @return the value of profile.createTime
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.createTime
     *
     * @param createTime the value for profile.createTime
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.active
     *
     * @return the value of profile.active
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public String getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.active
     *
     * @param active the value for profile.active
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setActive(String active) {
        this.active = active == null ? null : active.trim();
    }
    
    public Interestcard getInterestCard()
	{
		return interestCard;
	}

	public void setInterestCard(Interestcard interestCard)
	{
		this.interestCard = interestCard;
	}

	public Impresscard getImpressCard()
	{
		return impressCard;
	}

	public void setImpressCard(Impresscard impressCard)
	{
		this.impressCard = impressCard;
	}

	public void addProfileLog(Profileoperationlog log)
	{
		logQueue.add(log);
	}
	
	private Impresscard impressCard;
	private Interestcard interestCard;
	private ConcurrentLinkedQueue<Profileoperationlog> logQueue = new ConcurrentLinkedQueue<>();

	@Override
	public void save(SqlSession session)
	{
		ProfileMapper mapper = session.getMapper(ProfileMapper.class);
		if (this.profileId == null)
		{
			mapper.insert(this);
		}
		else
		{
			mapper.updateByPrimaryKey(this);
		}
		
		interestCard.setProfileId(profileId);
		interestCard.save(session);
		
		impressCard.setProfileId(profileId);
		impressCard.save(session);
		
		Profileoperationlog log;
		while(!logQueue.isEmpty())
		{
			log = logQueue.remove();
			log.setProfileId(profileId);
			log.save(session);
		}
	}
}