package com.simplelife.renhai.server.db;

import org.apache.ibatis.session.SqlSession;

import com.simplelife.renhai.server.util.IDbObject;

public class Sessionrecord implements IDbObject 
{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessionrecord.sessionRecordId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Integer sessionRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessionrecord.businessType
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private String businessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessionrecord.sessionStartTime
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Long sessionStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessionrecord.sessionDuration
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Integer sessionDuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessionrecord.chatStartTime
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Long chatStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessionrecord.chatDuration
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Integer chatDuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessionrecord.endStatus
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private String endStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessionrecord.endReason
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private String endReason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessionrecord.sessionRecordId
     *
     * @return the value of sessionrecord.sessionRecordId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Integer getSessionRecordId() {
        return sessionRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessionrecord.sessionRecordId
     *
     * @param sessionRecordId the value for sessionrecord.sessionRecordId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setSessionRecordId(Integer sessionRecordId) {
        this.sessionRecordId = sessionRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessionrecord.businessType
     *
     * @return the value of sessionrecord.businessType
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessionrecord.businessType
     *
     * @param businessType the value for sessionrecord.businessType
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setBusinessType(String businessType) {
        this.businessType = businessType == null ? null : businessType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessionrecord.sessionStartTime
     *
     * @return the value of sessionrecord.sessionStartTime
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Long getSessionStartTime() {
        return sessionStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessionrecord.sessionStartTime
     *
     * @param sessionStartTime the value for sessionrecord.sessionStartTime
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setSessionStartTime(Long sessionStartTime) {
        this.sessionStartTime = sessionStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessionrecord.sessionDuration
     *
     * @return the value of sessionrecord.sessionDuration
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Integer getSessionDuration() {
        return sessionDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessionrecord.sessionDuration
     *
     * @param sessionDuration the value for sessionrecord.sessionDuration
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setSessionDuration(Integer sessionDuration) {
        this.sessionDuration = sessionDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessionrecord.chatStartTime
     *
     * @return the value of sessionrecord.chatStartTime
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Long getChatStartTime() {
        return chatStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessionrecord.chatStartTime
     *
     * @param chatStartTime the value for sessionrecord.chatStartTime
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setChatStartTime(Long chatStartTime) {
        this.chatStartTime = chatStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessionrecord.chatDuration
     *
     * @return the value of sessionrecord.chatDuration
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Integer getChatDuration() {
        return chatDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessionrecord.chatDuration
     *
     * @param chatDuration the value for sessionrecord.chatDuration
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setChatDuration(Integer chatDuration) {
        this.chatDuration = chatDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessionrecord.endStatus
     *
     * @return the value of sessionrecord.endStatus
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public String getEndStatus() {
        return endStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessionrecord.endStatus
     *
     * @param endStatus the value for sessionrecord.endStatus
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setEndStatus(String endStatus) {
        this.endStatus = endStatus == null ? null : endStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessionrecord.endReason
     *
     * @return the value of sessionrecord.endReason
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public String getEndReason() {
        return endReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessionrecord.endReason
     *
     * @param endReason the value for sessionrecord.endReason
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setEndReason(String endReason) {
        this.endReason = endReason == null ? null : endReason.trim();
    }

	@Override
	public void save(SqlSession session)
	{
		SessionrecordMapper mapper = session.getMapper(SessionrecordMapper.class);
		mapper.insert(this);
	}
}