package com.simplelife.renhai.server.db;

import org.apache.ibatis.session.SqlSession;

import com.simplelife.renhai.server.util.IDbObject;

public class Systemstatistics implements IDbObject
{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemstatistics.systemStatisticsId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Integer systemStatisticsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemstatistics.saveTime
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Long saveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemstatistics.statisticsItemId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Integer statisticsItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemstatistics.count
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemstatistics.systemStatisticsId
     *
     * @return the value of systemstatistics.systemStatisticsId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Integer getSystemStatisticsId() {
        return systemStatisticsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemstatistics.systemStatisticsId
     *
     * @param systemStatisticsId the value for systemstatistics.systemStatisticsId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setSystemStatisticsId(Integer systemStatisticsId) {
        this.systemStatisticsId = systemStatisticsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemstatistics.saveTime
     *
     * @return the value of systemstatistics.saveTime
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Long getSaveTime() {
        return saveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemstatistics.saveTime
     *
     * @param saveTime the value for systemstatistics.saveTime
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setSaveTime(Long saveTime) {
        this.saveTime = saveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemstatistics.statisticsItemId
     *
     * @return the value of systemstatistics.statisticsItemId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Integer getStatisticsItemId() {
        return statisticsItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemstatistics.statisticsItemId
     *
     * @param statisticsItemId the value for systemstatistics.statisticsItemId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setStatisticsItemId(Integer statisticsItemId) {
        this.statisticsItemId = statisticsItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemstatistics.count
     *
     * @return the value of systemstatistics.count
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemstatistics.count
     *
     * @param count the value for systemstatistics.count
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setCount(Integer count) {
        this.count = count;
    }
    
    @Override
	public void save(SqlSession session)
	{
    	SystemstatisticsMapper mapper = session.getMapper(SystemstatisticsMapper.class);
		mapper.insert(this);
	}
}