package com.simplelife.renhai.server.db;

public class Systemoperationlog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemoperationlog.systemOperationLogId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Integer systemOperationLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemoperationlog.moduleId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Integer moduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemoperationlog.logTime
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Long logTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemoperationlog.operationCodeId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Integer operationCodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemoperationlog.logInfo
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private String logInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemoperationlog.systemOperationLogId
     *
     * @return the value of systemoperationlog.systemOperationLogId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Integer getSystemOperationLogId() {
        return systemOperationLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemoperationlog.systemOperationLogId
     *
     * @param systemOperationLogId the value for systemoperationlog.systemOperationLogId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setSystemOperationLogId(Integer systemOperationLogId) {
        this.systemOperationLogId = systemOperationLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemoperationlog.moduleId
     *
     * @return the value of systemoperationlog.moduleId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Integer getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemoperationlog.moduleId
     *
     * @param moduleId the value for systemoperationlog.moduleId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemoperationlog.logTime
     *
     * @return the value of systemoperationlog.logTime
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Long getLogTime() {
        return logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemoperationlog.logTime
     *
     * @param logTime the value for systemoperationlog.logTime
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setLogTime(Long logTime) {
        this.logTime = logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemoperationlog.operationCodeId
     *
     * @return the value of systemoperationlog.operationCodeId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Integer getOperationCodeId() {
        return operationCodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemoperationlog.operationCodeId
     *
     * @param operationCodeId the value for systemoperationlog.operationCodeId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setOperationCodeId(Integer operationCodeId) {
        this.operationCodeId = operationCodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemoperationlog.logInfo
     *
     * @return the value of systemoperationlog.logInfo
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public String getLogInfo() {
        return logInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemoperationlog.logInfo
     *
     * @param logInfo the value for systemoperationlog.logInfo
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setLogInfo(String logInfo) {
        this.logInfo = logInfo == null ? null : logInfo.trim();
    }
}