package com.simplelife.renhai.server.db;

import org.apache.ibatis.session.SqlSession;

import com.opentok.api.OpenTokSDK;
import com.simplelife.renhai.server.util.GlobalSetting;
import com.simplelife.renhai.server.util.IDbObject;
import com.simplelife.renhai.server.util.OpentokUtil;

public class Webrtcsession implements IDbObject 
{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webrtcsession.webRtcSessionId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Integer webRtcSessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webrtcsession.webrtcsession
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private String webrtcsession;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webrtcsession.requestDate
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Long requestDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webrtcsession.token
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webrtcsession.tokenUpdateDate
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Long tokenUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webrtcsession.expirationDate
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Long expirationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webrtcsession.webRTCAccountId
     *
     * @mbggenerated Mon Dec 02 14:30:44 CST 2013
     */
    private Integer webRTCAccountId;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webrtcsession.webRtcSessionId
     *
     * @return the value of webrtcsession.webRtcSessionId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Integer getWebRtcSessionId() {
        return webRtcSessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webrtcsession.webRtcSessionId
     *
     * @param webRtcSessionId the value for webrtcsession.webRtcSessionId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setWebRtcSessionId(Integer webRtcSessionId) {
        this.webRtcSessionId = webRtcSessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webrtcsession.webrtcsession
     *
     * @return the value of webrtcsession.webrtcsession
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public String getWebrtcsession() {
        return webrtcsession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webrtcsession.webrtcsession
     *
     * @param webrtcsession the value for webrtcsession.webrtcsession
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setWebrtcsession(String webrtcsession) {
        this.webrtcsession = webrtcsession == null ? null : webrtcsession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webrtcsession.requestDate
     *
     * @return the value of webrtcsession.requestDate
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Long getRequestDate() {
        return requestDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webrtcsession.requestDate
     *
     * @param requestDate the value for webrtcsession.requestDate
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setRequestDate(Long requestDate) {
        this.requestDate = requestDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webrtcsession.token
     *
     * @return the value of webrtcsession.token
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webrtcsession.token
     *
     * @param token the value for webrtcsession.token
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webrtcsession.tokenUpdateDate
     *
     * @return the value of webrtcsession.tokenUpdateDate
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Long getTokenUpdateDate() {
        return tokenUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webrtcsession.tokenUpdateDate
     *
     * @param tokenUpdateDate the value for webrtcsession.tokenUpdateDate
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setTokenUpdateDate(Long tokenUpdateDate) {
        this.tokenUpdateDate = tokenUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webrtcsession.expirationDate
     *
     * @return the value of webrtcsession.expirationDate
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Long getExpirationDate() {
        return expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webrtcsession.expirationDate
     *
     * @param expirationDate the value for webrtcsession.expirationDate
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setExpirationDate(Long expirationDate) {
        this.expirationDate = expirationDate == null ? null : expirationDate;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webrtcsession.webRTCAccountId
     *
     * @return the value of webrtcsession.webRTCAccountId
     *
     * @mbggenerated Mon Dec 02 14:30:44 CST 2013
     */
    public Integer getWebRTCAccountId() {
        return webRTCAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webrtcsession.webRTCAccountId
     *
     * @param webRTCAccountId the value for webrtcsession.webRTCAccountId
     *
     * @mbggenerated Mon Dec 02 14:30:44 CST 2013
     */
    public void setWebRTCAccountId(Integer webRTCAccountId) {
        this.webRTCAccountId = webRTCAccountId;
    }
    

	@Override
	public void save(SqlSession session)
	{
		WebrtcsessionMapper mapper = session.getMapper(WebrtcsessionMapper.class);
		mapper.insert(this);
	}
	
	public void updateToken(OpenTokSDK sdk)
	{
		Long now = System.currentTimeMillis();
		String token = OpentokUtil.updateToken(webrtcsession, sdk);
		setToken(token);
		setTokenUpdateDate(now);
		Long expire = now + GlobalSetting.BusinessSetting.OpenTokTokenExpiration * 1000; 
		setExpirationDate(expire);
		
		DAOWrapper.cache(this);
	}
}