package com.simplelife.renhai.server.db;

public class Webrtcaccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webrtcaccount.webRTCAccountId
     *
     * @mbggenerated Mon Dec 02 14:30:44 CST 2013
     */
    private Integer webRTCAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webrtcaccount.accountKey
     *
     * @mbggenerated Mon Dec 02 14:30:44 CST 2013
     */
    private Integer accountKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webrtcaccount.accountSecret
     *
     * @mbggenerated Mon Dec 02 14:30:44 CST 2013
     */
    private String accountSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webrtcaccount.loginAccount
     *
     * @mbggenerated Mon Dec 02 14:30:44 CST 2013
     */
    private String loginAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webrtcaccount.registerDate
     *
     * @mbggenerated Mon Dec 02 14:30:44 CST 2013
     */
    private Long registerDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webrtcaccount.webRTCAccountId
     *
     * @return the value of webrtcaccount.webRTCAccountId
     *
     * @mbggenerated Mon Dec 02 14:30:44 CST 2013
     */
    public Integer getWebRTCAccountId() {
        return webRTCAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webrtcaccount.webRTCAccountId
     *
     * @param webRTCAccountId the value for webrtcaccount.webRTCAccountId
     *
     * @mbggenerated Mon Dec 02 14:30:44 CST 2013
     */
    public void setWebRTCAccountId(Integer webRTCAccountId) {
        this.webRTCAccountId = webRTCAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webrtcaccount.accountKey
     *
     * @return the value of webrtcaccount.accountKey
     *
     * @mbggenerated Mon Dec 02 14:30:44 CST 2013
     */
    public Integer getAccountKey() {
        return accountKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webrtcaccount.accountKey
     *
     * @param accountKey the value for webrtcaccount.accountKey
     *
     * @mbggenerated Mon Dec 02 14:30:44 CST 2013
     */
    public void setAccountKey(Integer accountKey) {
        this.accountKey = accountKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webrtcaccount.accountSecret
     *
     * @return the value of webrtcaccount.accountSecret
     *
     * @mbggenerated Mon Dec 02 14:30:44 CST 2013
     */
    public String getAccountSecret() {
        return accountSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webrtcaccount.accountSecret
     *
     * @param accountSecret the value for webrtcaccount.accountSecret
     *
     * @mbggenerated Mon Dec 02 14:30:44 CST 2013
     */
    public void setAccountSecret(String accountSecret) {
        this.accountSecret = accountSecret == null ? null : accountSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webrtcaccount.loginAccount
     *
     * @return the value of webrtcaccount.loginAccount
     *
     * @mbggenerated Mon Dec 02 14:30:44 CST 2013
     */
    public String getLoginAccount() {
        return loginAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webrtcaccount.loginAccount
     *
     * @param loginAccount the value for webrtcaccount.loginAccount
     *
     * @mbggenerated Mon Dec 02 14:30:44 CST 2013
     */
    public void setLoginAccount(String loginAccount) {
        this.loginAccount = loginAccount == null ? null : loginAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webrtcaccount.registerDate
     *
     * @return the value of webrtcaccount.registerDate
     *
     * @mbggenerated Mon Dec 02 14:30:44 CST 2013
     */
    public Long getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webrtcaccount.registerDate
     *
     * @param registerDate the value for webrtcaccount.registerDate
     *
     * @mbggenerated Mon Dec 02 14:30:44 CST 2013
     */
    public void setRegisterDate(Long registerDate) {
        this.registerDate = registerDate;
    }
}