package com.simplelife.renhai.server.db;

public class Sessionprofilemap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessionprofilemap.sessionImpressMapId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Integer sessionImpressMapId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessionprofilemap.sessionRecordId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Integer sessionRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessionprofilemap.profileId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    private Integer profileId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessionprofilemap.sessionImpressMapId
     *
     * @return the value of sessionprofilemap.sessionImpressMapId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Integer getSessionImpressMapId() {
        return sessionImpressMapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessionprofilemap.sessionImpressMapId
     *
     * @param sessionImpressMapId the value for sessionprofilemap.sessionImpressMapId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setSessionImpressMapId(Integer sessionImpressMapId) {
        this.sessionImpressMapId = sessionImpressMapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessionprofilemap.sessionRecordId
     *
     * @return the value of sessionprofilemap.sessionRecordId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Integer getSessionRecordId() {
        return sessionRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessionprofilemap.sessionRecordId
     *
     * @param sessionRecordId the value for sessionprofilemap.sessionRecordId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setSessionRecordId(Integer sessionRecordId) {
        this.sessionRecordId = sessionRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessionprofilemap.profileId
     *
     * @return the value of sessionprofilemap.profileId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public Integer getProfileId() {
        return profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessionprofilemap.profileId
     *
     * @param profileId the value for sessionprofilemap.profileId
     *
     * @mbggenerated Fri Nov 01 15:18:11 CST 2013
     */
    public void setProfileId(Integer profileId) {
        this.profileId = profileId;
    }
}